name: worktest

on:
  workflow_dispatch:
env:
  global_env: "global variable"
jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "hello world"
  job-2:
    runs-on: ubuntu-24.04
    env:
      job_var: "hello world!!"
    steps:
      - name: test-1
        env:
          step_var: "next time !!"
        run: print("wow  ${{env.step_var}}")
        shell: python
  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - name: test-2
        run: print("next ${{env.global_env}}")
        shell: python
    
